import type { WebsiteContentConfig, WebsiteContentSection } from '../types/website-content';

export const websiteContentConfigs: WebsiteContentConfig[] = [
  {
    section: 'homepage',
    label: 'Homepage',
    singularLabel: 'Homepage Section',
    description: 'Control hero, featured content, homepage copy, and final CTA sections.',
    collection: 'website_pages',
    permission: 'website.homepage.manage',
    singleton: true,
    fields: [
      { key: 'eyebrow', label: 'Eyebrow', type: 'text' },
      { key: 'headline', label: 'Headline', type: 'textarea', required: true },
      { key: 'subtitle', label: 'Subtitle', type: 'textarea' },
      { key: 'primaryCtaLabel', label: 'Primary CTA Label', type: 'text' },
      { key: 'primaryCtaHref', label: 'Primary CTA Link', type: 'text' },
      { key: 'secondaryCtaLabel', label: 'Secondary CTA Label', type: 'text' },
      { key: 'secondaryCtaHref', label: 'Secondary CTA Link', type: 'text' },
    ],
  },
  {
    section: 'services',
    label: 'Services',
    singularLabel: 'Service',
    description: 'Manage service cards and service detail pages.',
    collection: 'website_services',
    permission: 'website.services.manage',
    requiresSlug: true,
    fields: [
      { key: 'shortTitle', label: 'Short Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea', required: true },
      { key: 'outcomes', label: 'Outcomes', type: 'list', description: 'One outcome per line.' },
      { key: 'deliverables', label: 'Deliverables', type: 'list', description: 'One deliverable per line.' },
      { key: 'ctaLabel', label: 'CTA Label', type: 'text' },
      { key: 'ctaHref', label: 'CTA Link', type: 'text' },
    ],
  },
  {
    section: 'apps',
    label: 'Apps & Case Studies',
    singularLabel: 'App / Case Study',
    description: 'Manage public apps, portfolio entries, and case studies.',
    collection: 'website_apps',
    permission: 'website.apps.manage',
    requiresSlug: true,
    requiresApproval: true,
    fields: [
      { key: 'summary', label: 'Summary', type: 'textarea', required: true },
      { key: 'problem', label: 'Problem', type: 'textarea' },
      { key: 'solution', label: 'Solution', type: 'textarea' },
      { key: 'results', label: 'Results', type: 'textarea' },
      { key: 'techStack', label: 'Technology Stack', type: 'list' },
      { key: 'imageUrl', label: 'Image URL', type: 'url' },
      { key: 'relatedServiceSlug', label: 'Related Service Slug', type: 'text' },
    ],
  },
  {
    section: 'blog',
    label: 'Blog',
    singularLabel: 'Blog Post',
    description: 'Manage blog posts, article content, categories, and SEO.',
    collection: 'website_blog_posts',
    permission: 'website.blog.manage',
    requiresSlug: true,
    fields: [
      { key: 'excerpt', label: 'Excerpt', type: 'textarea', required: true },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'tags', label: 'Tags', type: 'list' },
      { key: 'author', label: 'Author', type: 'text' },
      { key: 'coverImage', label: 'Cover Image URL', type: 'url' },
      { key: 'body', label: 'Body', type: 'textarea', required: true },
      { key: 'relatedSlugs', label: 'Related Slugs', type: 'list' },
    ],
  },
  {
    section: 'steps',
    label: 'Steps / Process',
    singularLabel: 'Step',
    description: 'Manage process and work-step content shown across the site.',
    collection: 'website_steps',
    permission: 'website.steps.manage',
    fields: [
      { key: 'number', label: 'Step Number', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea', required: true },
      { key: 'iconKey', label: 'Icon Key', type: 'text' },
      { key: 'relatedPage', label: 'Related Page', type: 'text' },
    ],
  },
  {
    section: 'faqs',
    label: 'FAQs',
    singularLabel: 'FAQ',
    description: 'Manage website FAQs and their related pages/services.',
    collection: 'website_faqs',
    permission: 'website.faqs.manage',
    fields: [
      { key: 'question', label: 'Question', type: 'textarea', required: true },
      { key: 'answer', label: 'Answer', type: 'textarea', required: true },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'relatedPage', label: 'Related Page', type: 'text' },
    ],
  },
  {
    section: 'pricing',
    label: 'Pricing',
    singularLabel: 'Pricing Package',
    description: 'Manage pricing packages, features, and package CTAs.',
    collection: 'website_pricing_packages',
    permission: 'website.pricing.manage',
    fields: [
      { key: 'description', label: 'Description', type: 'textarea', required: true },
      { key: 'priceLabel', label: 'Price Label', type: 'text' },
      { key: 'features', label: 'Features', type: 'list' },
      { key: 'recommended', label: 'Recommended', type: 'toggle' },
      { key: 'ctaLabel', label: 'CTA Label', type: 'text' },
      { key: 'ctaHref', label: 'CTA Link', type: 'text' },
    ],
  },
  {
    section: 'testimonials',
    label: 'Testimonials',
    singularLabel: 'Testimonial',
    description: 'Manage approved public testimonials.',
    collection: 'website_testimonials',
    permission: 'website.testimonials.manage',
    requiresApproval: true,
    fields: [
      { key: 'quote', label: 'Quote', type: 'textarea', required: true },
      { key: 'author', label: 'Author', type: 'text', required: true },
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'company', label: 'Company', type: 'text' },
      { key: 'avatarUrl', label: 'Avatar URL', type: 'url' },
    ],
  },
  {
    section: 'partners',
    label: 'Partners',
    singularLabel: 'Partner',
    description: 'Manage approved partner names, logos, and links.',
    collection: 'website_partners',
    permission: 'website.partners.manage',
    requiresApproval: true,
    fields: [
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'logoUrl', label: 'Logo URL', type: 'url' },
      { key: 'websiteUrl', label: 'Website URL', type: 'url' },
      { key: 'category', label: 'Category', type: 'text' },
    ],
  },
  {
    section: 'team',
    label: 'Team',
    singularLabel: 'Team Member',
    description: 'Manage team members shown on the public website.',
    collection: 'website_team_members',
    permission: 'website.team.manage',
    fields: [
      { key: 'role', label: 'Role', type: 'text', required: true },
      { key: 'bio', label: 'Bio', type: 'textarea' },
      { key: 'photoUrl', label: 'Photo URL', type: 'url' },
      { key: 'socialLinks', label: 'Social Links', type: 'list' },
    ],
  },
  {
    section: 'careers',
    label: 'Careers',
    singularLabel: 'Career Role',
    description: 'Manage open roles and hiring content.',
    collection: 'website_careers',
    permission: 'website.careers.manage',
    requiresSlug: true,
    fields: [
      { key: 'department', label: 'Department', type: 'text' },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'workType', label: 'Work Type', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea', required: true },
      { key: 'requirements', label: 'Requirements', type: 'list' },
      { key: 'applyHref', label: 'Apply Link or Email', type: 'text' },
    ],
  },
  {
    section: 'legal',
    label: 'Legal Pages',
    singularLabel: 'Legal Page',
    description: 'Manage privacy, terms, and legal copy.',
    collection: 'website_legal_pages',
    permission: 'website.legal.manage',
    requiresSlug: true,
    fields: [
      { key: 'content', label: 'Content', type: 'textarea', required: true },
      { key: 'lastReviewedAt', label: 'Last Reviewed Date', type: 'text' },
      { key: 'reviewedBy', label: 'Reviewed By', type: 'text' },
      { key: 'reviewNotes', label: 'Review Notes', type: 'textarea' },
    ],
  },
  {
    section: 'settings',
    label: 'Site Settings',
    singularLabel: 'Site Settings',
    description: 'Manage global site identity, contact details, social links, and default SEO.',
    collection: 'website_settings',
    permission: 'website.settings.manage',
    singleton: true,
    fields: [
      { key: 'siteName', label: 'Site Name', type: 'text', required: true },
      { key: 'englishName', label: 'English Name', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'logoUrl', label: 'Logo URL', type: 'url' },
      { key: 'defaultOgImage', label: 'Default OG Image', type: 'url' },
      { key: 'socialLinks', label: 'Social Links', type: 'list' },
    ],
  },
];

export const websiteContentConfigMap = websiteContentConfigs.reduce((acc, config) => {
  acc[config.section] = config;
  return acc;
}, {} as Record<WebsiteContentSection, WebsiteContentConfig>);

export function getWebsiteContentConfig(section: WebsiteContentSection) {
  return websiteContentConfigMap[section];
}
